name: CI Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with HTML report
      run: pytest --html=reports/report.html --self-contained-html
    - name: Run tests with Allure
      run: pytest --alluredir=reports/allure-results
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results
